# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Build Doc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-doc:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Python runtime
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64

      - name: Install Python dependencies
        run: |
          pip3 install -U -r requirements.txt

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Node dependencies
        run: |
          yarn

      - name: Build
        run: |
          cd oi-wiki
          git ls-files | while read filepath; do touch -d "$(git log -1 --format='@%ct' $filepath)" "$filepath" && echo "Fixed: $filepath"; done
          cd ..
          cp -a ./oi-wiki/docs docs
          yarn build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 🚀 Deploying to gh-pages @ ${{ env.GITHUB_SHA }}
