# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Build Doc

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build-doc:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Update Submodule
        run: |
          git submodule update --recursive --remote

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 🚀 Update OI-WiKi
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'

      - name: Set up Python runtime
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm

      - name: Install Node dependencies
        run: |
          pnpm i

      - name: Fix mtime
        run: |
          cd oi-wiki
          git ls-files | while read filepath; do touch -d "$(git log -1 --format='@%ct' $filepath)" "$filepath" && echo "Fixed: $filepath"; done
          cd ..

      - name: Build
        run: |
          cp -a ./oi-wiki/docs docs
          pnpm build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 🚀 Deploying to gh-pages @ ${{ env.GITHUB_SHA }}
